### ISSUE TITLE
No image examples in the "examples" folder

### ISSUE THREAD

**Issue by valeriobellucci** [APS-XSD-OPT-Group/wavepy#33]
the scripts in the "examples" folder are supposed to import tiff images, ex. 'data_example_for_single_grating/cb4p8um_halfPi_8KeV_10s_img.tif' that are not present

**Comment by lucarebuffi** [comment]
Dear Valerio,

we are not maintaining wavy anymore. Please take a look to [wavepy2](https://github.com/APS-XSD-OPT-Group/wavepy2)
